### ISSUE TITLE
fishnet & computer analysis on lichess

### ISSUE THREAD

**Issue by lazydroid** [niklasf/fishnet#123]
I'm running a fishnet node, and I have recently bumped into the computer analysis being not available (redirects to the same page) on lichess. I understand that this is probably not a fishnet issue per se, but still, I wonder, if any of the following is possible:

* get some credits for running a fishnet node and maybe have a tad higher daily analysis limit
* get a clearer indication about the limits, how many are remaining, because the web site says "30 per day" (lichess.org/features) and I hardly could get more than 7 or 8 (did I hit a weekly or monthly quota or something? I don't know and there's no way to know)

thanks!

**Comment by niklasf** [comment]
Thanks for running fishnet!

There is currently a bug with the limits, so that they are effectively only half as high as intended. The next update should fix that. That should already help a lot.

Probably no to your first point. It makes sense, but I don't like it from a technical standpoint. We will keep watching if we can increase the limits for all, after the bugfix.

Definitely yes to your second point. Especially when the page just reloads after clicking the button, there should instead be a clear indication what went wrong.

**Comment by jim-perkins** [comment]
lots of talk on the https://lichess.org/forum/lichess-feedback  feedback forum.  I do recall seeing one post that pointed to the exact lines in code

https://lichess.org/page/changelog
November 9th, 2020
Stricter limits on the amount of Fishnet game analysis that users can request. 25 per day/100 per week now allowed per account. (These limits subject to change)

https://lichess.org/forum/lichess-feedback/whats-with-analysis-limit#5
max requests Per Day = 25.
max requests Per Week = 100.
After 50 games (week) only 12 per day are possible.
Analyze other games than your own count double.

https://lichess.org/terms-of-service
Premium accounts
Lichess will never create premium accounts.

**Comment by lazydroid** [comment]
> Analyze other games than your own count double.

oh, this is very unexpected. thanks, guys!
a friend of mine is teaching chess to kids, I might have looked over a few games of the students of him.
