### ISSUE TITLE
Docker reports manual upgrade necessary

### ISSUE THREAD

**Issue by teotwaki** [niklasf/fishnet#130]
Hi,

I noticed that the auto-updated docker version of fishnet is now reporting that a manual upgrade step is required. It points to this repository:

![fishnet-update](https://user-images.githubusercontent.com/1420434/100600403-8a1be580-3301-11eb-8e80-257425e1f35b.png)

I noticed that you have some commits mentioning preparations for version 2.0. I'm happy to contribute a new docker image if it is needed (I see that you switched from Python to Rust), and can also help out with some Rust code if needed. I use docker-compose to host fishnet, so I could provide a sample file for that as well.

Best,

PS: [upx](https://upx.github.io/) is a fantastic tool if you're trying to keep binary file size down. I usually end up with files between 20-30% of their original size through UPX.

**Comment by niklasf** [comment]
Hi, yes, a new Dockerfile would be great, for people who prefer that instead of the standalone binary. For reference, here is the previous one: https://github.com/niklasf/fishnet/blob/1.x/Dockerfile

**Comment by teotwaki** [comment]
Would you prefer the Dockerfile fetches/downloads the pre-built binaries from GitHub/elsewhere, or builds them from source?

**Comment by niklasf** [comment]
Mhh, not sure. I don't have much experience using Docker. Do you have an idea what most Docker users would prefer?

**Comment by teotwaki** [comment]
I don't think it matters much. I'll send you some PRs tonight.

**Comment by niklasf** [comment]
Thanks for the pull requests, @teotwaki and @sykoe! My thoughts:

* I would prefer to pass arguments through to `ENTRYPOINT` rather than environment variables and `RUN`, unless there's a technical reason not to.
* I realize now that building from source requires duplicating the build steps. There are not many now (just `cargo build --release` and `strip`), but that might change (#131). So perhaps we should just go with the binary?
* If we go that route, then triggering the build immediately on push would not work, because it needs to wait for the binary to be uploaded.
* I have created https://hub.docker.com/repository/docker/niklasf/fishnet and added `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` to the secret store of this repository, in case that's still useful to make progress.
* We'll have to check that the Stockfish processes are reaped when the container is shut down. The Python client required adding `dumb-init`. Perhaps Rust is better at cleaning up.

**Comment by teotwaki** [comment]
The main reason to use environment variables is because that's the current best practice (see https://12factor.net/). Simple environment variables are easier to manage than generating a string of options. I don't start my dockers manually. I have orchestrators that do that for me, meaning that I don't actually ever write an entire command line to start a service, I just write yaml files.

I haven't noticed any reaping issues during my testing. How did this manifest itself previously?

**Comment by niklasf** [comment]
Alright, environment variables it is, then. Maybe still `ENTRYPOINT`, to be able to pass less frequently used options (like `-v` for debugging)?

It was Stockish processes sticking around as zombies in `ps ax | grep stockfish`, even after the container shut down. It was happening reliably, so if it's not an issue now, I don't expect it to start happening randomly.

**Comment by teotwaki** [comment]
This could still be triggered again if we switch to ENTRYPOINT. We might need a shell wrapper. I'll do some tests and report back. Don't think I'll have time before tomorrow though.

**Comment by thesilican** [comment]
@teotwaki I have a PR prepared with shell wrapper, will post in about 2-3 hours

**Comment by niklasf** [comment]
Oh, sorry. I also gave it a try based on the discussion so far (it's on current master), so that might be conflicting now. Improvements welcome, of course.
