### ISSUE TITLE
Status message formatting proposal

### ISSUE THREAD

**Issue by lenik-covert** [niklasf/fishnet#142]
I know I'm beating an old horse, but I find this format for the status message more appealing:

`Analyzed 154 positions, crunched 601.91M nodes`

The required changes:

```
above1 = [ ('Z', 1e21), ('E', 1e18), ('P', 1e15), ('T', 1e12), ('G', 1e9), ('M', 1e6), ('k', 1e3) ]
below1 = [ ('m', 1e-3), ('μ', 1e-6), ('n', 1e-9), ('p', 1e-12), ('f', 1e-15), ('a', 1e-18), ('z', 1e-21) ]

def format_number( num ) :
	suffix = ''
	divisor = 1.0
	if num > 1.0 :
		for a,b in above1[::-1] :
			if num > b :
				suffix = a
				divisor = b
	else :
		for a,b in below1[::-1] :
			if num > b :
				suffix = a
				divisor = b

	return str(num) if divisor == 1.0 else '%.02f%s' % (num/divisor, suffix)
```

and then:

```
# Log stats
logging.info("[fishnet v%s] Analyzed %s positions, crunched %s nodes",
			__version__,
			format_number(sum(worker.positions for worker in workers)),
			format_number(sum(worker.nodes for worker in workers)))
```
Please, feel free to implement something similar or reject it altogether =)

**Comment by niklasf** [comment]
I did something like that for a moment (cd0cbd4c3c4530c6579a3f70637cb965ee55cdd3), but reverted it again, because the least significant digits can be used to tell if a long running instance is somehow hanging. I guess i'll just add thousands separators.

**Comment by jim-perkins** [comment]
:-)  

https://www.bipm.org/en/CGPM/db/22/10/

**reaffirms that "Numbers may be divided in groups of three in order to facilitate reading; neither dots nor commas are ever inserted in the spaces between groups", as stated in Resolution 7 of the 9th CGPM, 1948.**

Was just reviewing my logs and wondered how the dot vs comma thing ever got started.  The older I get the more history engages me.  Anyway, whatever works for you is fine for me now that I realize what I am looking at.  Here's wishing you all a Great 2021.
