### ISSUE TITLE
Can’t find Stockfish in scope

### ISSUE THREAD

**Issue by mayweed** [niklasf/fishnet#159]
Hello Niklas,
Am trying to update my current Pi setting with the new rust fishnet and while running cargo i got this error:

```
Compiling fishnet v2.2.1-dev (/home/pi/fishnet)
error[E0425]: cannot find value `STOCKFISH` in this scope
   --> src/assets.rs:425:18
    |
425 |         let sf = STOCKFISH.iter().find(|a| cpu.contains(a.needs)).expect("compatible stockfish");
    |                  ^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `STOCKFISH_MV` in this scope
   --> src/assets.rs:431:32
    |
431 |                 multi_variant: STOCKFISH_MV.iter().find(|a| cpu.contains(a.needs)).expect("compatible stockfish").create(dir.path())?,
    |                                ^^^^^^^^^^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `fishnet`

To learn more, run the command again with --verbose.

```
Is this because there is no official release of SF for armv7? Se is there an option to pass a self compile sf?
Guillaume

**Comment by niklasf** [comment]
The current decision is to draw the line for platform support at 64 bit. To check, can you please share the output of `./self-compiled-stockfish bench`? I suspect it will be too slow.

**Comment by mayweed** [comment]
Here are the 3 last lines:
```
===========================
Total time (ms) : 20156
Nodes searched  : 5156767
Nodes/second    : 255842
```
Thx
Guillaume

**Comment by niklasf** [comment]
Thanks. Currently, the absolutely minimum acceptable nodes/second is 375000. Looks like the Raspberry could achieve it when using multiple threads, but barely, and it would probably get very hot, unless actively cooled. I don't think it's worth it.

The reason it's now harder to use custom Stockfish builds is that since version 2 the goal is to deliver exactly identical analysis no matter which fishnet client does the analysis, so the exact reproducible builds of Stockfish are tracked in Git.
