### ISSUE TITLE
memory configuration

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#19]
in the config file, let people declare how much memory they want to give fishnet in total; distribute it to the stockfish processes.

**Comment by niklasf** [comment]
Makes sense. Is there a point where we rather have fewer processes with more memory each?

**Comment by ornicar** [comment]
I don't think so.

**Comment by ornicar** [comment]
But we might refuse to start fishnet if the memory per process is < 32m.

**Comment by niklasf** [comment]
@ddugovic: do you have any insights on optimal transposition table sizes?

**Comment by ddugovic** [comment]
I've been deferring to Stockfish default hash table size and default values set in base.conf.  Obviously increasing the hash table size allows it to search deeper since the hash table hit rate increases.

I know even with little memory Stockfish does run, though I haven't tested how much its rating degrades.  I have a test suite I was using to try to gauge its rating... I'll run some tests and see how it degrades.

**Comment by niklasf** [comment]
awesome. thanks!

**Comment by niklasf** [comment]
this is now configurable: `[Fishnet] Memory = ... ; Mb`
