### ISSUE TITLE
Feature request for more stats...

### ISSUE THREAD

**Issue by ysageev** [niklasf/fishnet#97]
Hi,

I just want a few features which I hope would be easy to implement:

1. Persistent statistics
 a. Total number of games analyzed since installed, broken down by type (chess, crazyhouse, etc)
 b. Average time to analyze a whole game (not position)
 c. Average number of moves per game

2. Per session statistics
 a. Total games analyzed
 b. Time running

Thanks!

**Comment by zagaberoo** [comment]
I'd like something like this as well.

Even a simple page where I could drop in my api key and see how many games I've analyzed would be really satisfying.

**Comment by Eugenio-Bruno** [comment]
I'd like to *try* to work on this, since it's something I've also wanted. It would be my first open source contribution and I'd probably need a bit of hand holding through the process of sending a PR, doing code review and so on.

Would that be alright?

As to how I'd do this, I was thinking of having, at least to start, an optional setting to specify a path to an sqlite database, that would get created if it doesn't exist, so we can store all kind of statistics. As a proof of concept, I'd start by just storing total amount of games, of moves, nodes, time, all per-variant, in a single table. After we get that working and the code looks good, I can start working on more interesting statistics and data collection.

This would all be local.
